<a href="https://colab.research.google.com/github/shreshthajit/ML_Lab/blob/main/KFold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
import pandas as pd

#digits = load_digits()

In [ ]:
#digits

In [ ]:
data_path = './sample_data/nn_data.txt'
dataset = pd.read_csv(data_path, header=None)
dataset.shape
print(dataset.head())

   0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1


In [ ]:
from sklearn.model_selection import train_test_split
X = dataset.iloc[:,0:8]
y = dataset.iloc[:,8]
#dataset.head()
#y

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0)

**KFOLD corss validation**

In [ ]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(X,y):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [ ]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [ ]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [ ]:
scores_rf

[0.9432387312186978, 0.9532554257095158, 0.9232053422370617]

**Cross_val_score function**

In [ ]:
from sklearn.model_selection import cross_val_score

**Logistic regression model performance using cross_val_score**

In [ ]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X,y,cv=3)

array([0.75      , 0.76171875, 0.796875  ])

**svm model performance using cross_val_score**

In [ ]:
cross_val_score(SVC(gamma='auto'), X, y,cv=3)

array([0.6484375 , 0.65234375, 0.65234375])

**random forest performance using cross_val_score**

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=40),X,y,cv=3)

array([0.72265625, 0.734375  , 0.76171875])

**Parameter tunning using k fold cross validation**

In [ ]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),X,y, cv=10)
np.average(scores1)

0.7188311688311689

In [ ]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),X,y, cv=10)
np.average(scores2)

0.7409432672590568

In [ ]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),X,y, cv=10)
np.average(scores3)

0.7526315789473684

In [ ]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),X,y, cv=10)
np.average(scores4)

0.7395762132604238